 "use client";

import "./globals.css";

import { createContext, useState,useEffect } from "react";
import { Header } from "@/components/header";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const TokenContext = createContext();

export default function RootLayout({ children }) {
  const [token, setToken] = useState(""); // Initialize token state

  useEffect(() => {
    // Check if localStorage is defined before accessing it
    if (typeof window !== 'undefined') {
      const storedToken = localStorage.getItem("token"); // Access localStorage
      if (storedToken) {
        setToken(storedToken);
      }
    }
  }, []);
  return (
    <html>
      <body>
        <TokenContext.Provider value={{ token, setToken }}>
          <Header />
          {children}
        </TokenContext.Provider>
      </body>
    </html>
  );
}